
export const WORD_LIST = [  'APPLE', 'GRAPE', 'LEMON', 'PEACH', 'BERRY', 'MELON', 'MANGO', 'PLUMB', 'OLIVE', 'PEARL',
    'ONION', 'SPICE', 'BREAD', 'CHEESE', 'HONEY', 'CREAM', 'COCOA', 'SUGAR', 'CIDER', 'BUTTER',
    'PIZZA', 'SALAD', 'SAUCE', 'PASTA', 'BACON', 'TOAST', 'EGG', 'BEANS', 'STEAK', 'NACHO',
    'TACOS', 'QUAIL', 'BISON', 'MINTS', 'WHEAT', 'LEEKS', 'CORNS', 'SUSHI', 'DONUT', 'YEAST',
    'ZEBRA', 'WHALE', 'TIGER', 'GOOSE', 'HORSE', 'SHARK', 'LEMUR', 'KOALA', 'PANDA', 'OTTER',
    'VIPER', 'MOUSE', 'CAMEL', 'SHEEP', 'COBRA', 'RAVEN', 'DINGO', 'PUMA', 'LIONS', 'GEESE',
    'SWANS', 'LLAMA', 'SNAIL', 'MOLE', 'DEER', 'FROG', 'MOOSE', 'SLOTH', 'BABOON', 'ZEBRA',
    'ZOMBI', 'HUMOR', 'CLOWN', 'MUSIC', 'PIANO', 'DRUMS', 'DANCE', 'COMEDY', 'GUITAR', 'SING',
    'LAUGH', 'SMILE', 'FUNNY', 'PARTY', 'CHEER', 'JOKER', 'HAPPY', 'PUZZL', 'MIRTH', 'CHARM',
    'BLISS', 'WITTY', 'KNIFE', 'QUEEN', 'JUMPY', 'FROST', 'VIVID', 'QUICK', 'FLAIR', 'BRICK',
    'CRISP', 'DUCKS', 'GLORY', 'HEXES', 'TWIRL', 'VIXEN', 'DWARF', 'AXIOM', 'JOKES', 'MIGHT',
    'WORST', 'CLAMP', 'FLUID', 'GLINT', 'PIXEL', 'TRACK', 'YOUTH', 'GLOBE', 'QUEST'];